### ISSUE TITLE
Possible code Bug

### ISSUE THREAD

**Issue by gustavomodelli** [voigtstefan/tidy_finance#13]
I was reproducing the code bellow and did not working properly.

returns <- prices |>
  arrange(date) |>
  mutate(ret = adjusted / lag(adjusted) - 1) |>
  select(symbol, date, ret)
returns

I tinck the formula needs a parenthesis

returns <- prices |>
  arrange(date) |>
  mutate(ret = (adjusted / lag(adjusted)) - 1) |>
  select(symbol, date, ret)
returns

**Comment by voigtstefan** [comment]
Hi Gustavo,
Thanks for your comment! Could you let ud know what did not work "properly" in your opinion? I do not see why the brackets should produce a different output than what we propose so far..
Thanks for your help,
Best,
Stefan

**Comment by gustavomodelli** [comment]
Dear Voigt,



I would like to congratulations you for the excellent work in tidy finance.

The formula: pt / pt-1 -1 when code in R: adjusted / lag(adjusted) -1
produces different effect than the proposed formula (adjusted /
lag(adjusted) ) -1.

The R was computing first subtraction and after de division. The brackets
guide the operation first to the division and after the subtraction.

Although, this was not uniform because I tested now, and the code were
working properly without the brackets.



Sincerely,
Luis Gustavo Modelli de Andrade
Médico Nefrologista HC UNESP
http://lattes.cnpq.br/0137934364618584



Em qua., 27 de jul. de 2022 às 04:30, Stefan Voigt ***@***.***>
escreveu:

**Comment by christophscheuch** [comment]
The brackets do not make a difference. For future checks, you could use `all.equal()`:
`library(tidyverse)
library(tidyquant)

prices <- tq_get("AAPL",
                 get = "stock.prices",
                 from = "2000-01-01",
                 to = "2022-06-30"
)

returns <- prices |>
  arrange(date) |>
  mutate(ret = adjusted / lag(adjusted) - 1) |>
  select(symbol, date, ret)

returns2 <- prices |>
  arrange(date) |>
  mutate(ret = (adjusted / lag(adjusted)) - 1) |>
  select(symbol, date, ret)

all.equal(returns, returns2)`

**Comment by gustavomodelli** [comment]
Dear Scheuch,


Thank you for the response.

Luis Gustavo Modelli de Andrade
Médico Nefrologista HC UNESP
http://lattes.cnpq.br/0137934364618584



Em qua., 27 de jul. de 2022 às 13:50, Christoph Scheuch <
***@***.***> escreveu:
